### ISSUE TITLE
Mark Modded Games in Lobby

### ISSUE THREAD

**Issue by TomRichter** [PULSAR-Modders/pulsar-mod-loader#13]
Modded games announce themselves through Photon Properties as `isModded`.  The game lobby should use this property to identify modded games, similar to the Discord game list bot.  Look at how the lock icon is added for inspiration.

**Comment by DragonFire47** [comment]
Feature added with 0.10.1. Lobbies now show a '<color=yellow>M</color>' when the isModded tag exists.
