### ISSUE TITLE
README refers to plugins folder

### ISSUE THREAD

**Issue by 18107** [PULSAR-Modders/pulsar-mod-loader#29]
The plugins folder has been renamed to mods in the code but not in the readme

**Comment by BadRyuner** [comment]
Also in  "Basic Plugin Example" written **_protected_** override string HarmonyIdentifier instead of **_public_** override string HarmonyIdentifier.

**Comment by 18107** [comment]
Fixed in a521732989823d846e1379eb1cdecd3422adddec and 3027de481ada17727c0e2ac6abe8c4f25ca7bbe8
