### ISSUE TITLE
F5 ModManager improvements

### ISSUE THREAD

**Issue by DragonFire47** [PULSAR-Modders/pulsar-mod-loader#35]
ModManager has a number of UI issues.
-Users are able click buttons behind GUI, which means the user has to move the manager around to avoid unintentional button clicking.
-Users must manually unlock the mouse when interacting with the GUI. Should have an option for toggling so users can keep the menu up while playing. 
-deselecting text input fields is unintuitive, right click seems to be the best method.

**Comment by BadRyuner** [comment]
We can switch to [UniverseLib](https://github.com/sinai-dev/UniverseLib), but then mods that uses F5 menu will break

**Comment by DragonFire47** [comment]
Improvements!!!

- Users can no longer click through the mod manager in most cases, apart from a few pulsar-dev related situations (Ship Screens, + Levers)
- Cursor and player camera are now unlocked while the manager is open. Can be toggled via PML settings page.

Input fields haven't been touched, right-clicking and clicking anywhere that isn't the mod manager deselects the text box. I'm gonna close this for now, as this is a major improvement.
