### ISSUE TITLE
Wiki link to PPL.CE is broken

### ISSUE THREAD

**Issue by cspotcode** [PULSAR-Modders/pulsar-mod-loader#40]
The link to PPL.CE on this wiki page is broken:

https://github.com/PULSAR-Modders/pulsar-mod-loader/wiki/Useful-Tools

The link points to:

https://github.com/TomRichter/PPL.CommonExtensions

**Comment by DragonFire47** [comment]
PPL Common Extensions was merged with PPL a long time ago. The link will be removed, thanks for bringing it to our attention.
