### ISSUE TITLE
dnSpy vs dnSpyEx

### ISSUE THREAD

**Issue by cspotcode** [PULSAR-Modders/pulsar-mod-loader#41]
dnSpy is archived and unmaintained.
https://github.com/dnSpy/dnSpy/

I see that there is another project, dnSpyEx, that aims to continue maintenance and release new versions.
https://github.com/dnSpyEx/dnSpy

Do Pulsar modders use one or the other?  Are there any reasons to prefer one or the other, perhaps because dnSpyEx removed an important feature, or because dnSpy already does everything you need and so there is no reason to upgrade?

**Comment by DragonFire47** [comment]
The old repository has been functional, so there hasn't been a need to move over. I wasn't aware of dnSpyEx until you mentioned it, so I'll take a look to see what's new.

**Comment by DragonFire47** [comment]
Having used dnSpyEx for a little bit, it's nice but doesn't have any noteworthy features over the original. I believe it does have a number of improvements, but for now I'll leave the original dnSpy link. Should someone feel they need something newer, they can test the waters for themselves. 

TL:DR; No major reasons to upgrade.
