### ISSUE TITLE
Wiki refers to Plugins, predating the rename to Mods

### ISSUE THREAD

**Issue by cspotcode** [PULSAR-Modders/pulsar-mod-loader#42]
Wiki pages appear to be written against old versions of pulsar-mod-loader

For example, this page refers to `PulsarPlugin` instead of `PulsarMod`
https://github.com/PULSAR-Modders/pulsar-mod-loader/wiki/Creating-Plugins

This page talks about copying mods into `<game dir>/PULSAR_LostColony_Data/Managed/Plugins`, but they should go into `<game dir>/Mods`
https://github.com/PULSAR-Modders/pulsar-mod-loader/wiki/Visual-Studio-Tips

Some of the wiki's information is replicated in the README. so one of the two duplicates could be removed.  The page about configuring `.csproj`, however, is not duplicated in the README.  I found it useful, so I think it should be preserved somewhere, whether in the wiki or README or elsewhere.

**Comment by DragonFire47** [comment]
I've updated the wiki page in question, as well as added a number of new pages focused on PML features.

I'll look into removing the mod development info from the README in the near future.
